package jmx

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/devaryakjha/loadwright/internal/spec"
)

func SafeName(value string) string {
	re := regexp.MustCompile(`[^A-Za-z0-9_.-]+`)
	cleaned := strings.Trim(re.ReplaceAllString(strings.TrimSpace(value), "-"), "-")
	if cleaned == "" {
		return "test"
	}
	return cleaned
}

func Compile(s *spec.Spec, outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(Render(s)), 0o644)
}

func Render(s *spec.Spec) string {
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString(`<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">` + "\n")
	b.WriteString("  <hashTree>\n")
	writeTestPlan(&b, s)
	b.WriteString("    <hashTree>\n")
	writeThreadGroup(&b, s)
	b.WriteString("      <hashTree>\n")
	writeDataSets(&b, s)
	for _, request := range s.Requests {
		if request.Protocol == "websocket" {
			writeWebSocketSampler(&b, s, request)
			continue
		}
		writeHTTPSampler(&b, s, request)
	}
	b.WriteString("      </hashTree>\n")
	b.WriteString("    </hashTree>\n")
	b.WriteString("  </hashTree>\n")
	b.WriteString("</jmeterTestPlan>\n")
	return b.String()
}

func writeDataSets(b *strings.Builder, s *spec.Spec) {
	for _, name := range sortedDataSetNames(s.Data) {
		dataSet := s.Data[name]
		fmt.Fprintf(b, `        <CSVDataSet guiclass="TestBeanGUI" testclass="CSVDataSet" testname="%s" enabled="true">`+"\n", esc(name))
		fmt.Fprintf(b, "          <stringProp name=\"filename\">%s</stringProp>\n", esc(dataSet.File))
		fmt.Fprintf(b, "          <stringProp name=\"fileEncoding\">UTF-8</stringProp>\n")
		fmt.Fprintf(b, "          <stringProp name=\"variableNames\">%s</stringProp>\n", esc(strings.Join(dataSet.Variables, ",")))
		fmt.Fprintf(b, "          <boolProp name=\"ignoreFirstLine\">true</boolProp>\n")
		fmt.Fprintf(b, "          <stringProp name=\"delimiter\">,</stringProp>\n")
		fmt.Fprintf(b, "          <boolProp name=\"quotedData\">false</boolProp>\n")
		fmt.Fprintf(b, "          <boolProp name=\"recycle\">%s</boolProp>\n", boolString(dataSet.Recycle, true))
		fmt.Fprintf(b, "          <boolProp name=\"stopThread\">%s</boolProp>\n", boolString(dataSet.StopThread, false))
		fmt.Fprintf(b, "          <stringProp name=\"shareMode\">%s</stringProp>\n", esc(shareMode(dataSet.Sharing)))
		b.WriteString("        </CSVDataSet>\n")
		b.WriteString("        <hashTree/>\n")
	}
}

func writeTestPlan(b *strings.Builder, s *spec.Spec) {
	fmt.Fprintf(b, `    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="%s" enabled="true">`+"\n", esc(s.Name))
	b.WriteString("      <stringProp name=\"TestPlan.comments\">Generated by Loadwright from a YAML spec.</stringProp>\n")
	b.WriteString("      <boolProp name=\"TestPlan.functional_mode\">false</boolProp>\n")
	b.WriteString("      <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>\n")
	b.WriteString("      <elementProp name=\"TestPlan.user_defined_variables\" elementType=\"Arguments\" guiclass=\"ArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\n")
	b.WriteString("        <collectionProp name=\"Arguments.arguments\"/>\n")
	b.WriteString("      </elementProp>\n")
	b.WriteString("      <stringProp name=\"TestPlan.user_define_classpath\"></stringProp>\n")
	b.WriteString("    </TestPlan>\n")
}

func writeThreadGroup(b *strings.Builder, s *spec.Spec) {
	fmt.Fprintf(b, `      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="%s users" enabled="true">`+"\n", esc(s.Name))
	b.WriteString("        <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>\n")
	b.WriteString("        <elementProp name=\"ThreadGroup.main_controller\" elementType=\"LoopController\" guiclass=\"LoopControlPanel\" testclass=\"LoopController\" testname=\"Loop Controller\" enabled=\"true\">\n")
	continueForever := "false"
	loops := "1"
	if s.Load.Duration.Set {
		continueForever = "true"
		loops = "-1"
	} else if s.Load.Loops != nil {
		loops = fmt.Sprintf("%d", *s.Load.Loops)
	}
	fmt.Fprintf(b, "          <boolProp name=\"LoopController.continue_forever\">%s</boolProp>\n", continueForever)
	fmt.Fprintf(b, "          <stringProp name=\"LoopController.loops\">%s</stringProp>\n", loops)
	b.WriteString("        </elementProp>\n")
	fmt.Fprintf(b, "        <stringProp name=\"ThreadGroup.num_threads\">%d</stringProp>\n", s.Load.Users)
	fmt.Fprintf(b, "        <stringProp name=\"ThreadGroup.ramp_time\">%d</stringProp>\n", s.Load.RampUp.Seconds)
	b.WriteString("        <boolProp name=\"ThreadGroup.same_user_on_next_iteration\">true</boolProp>\n")
	if s.Load.Duration.Set {
		b.WriteString("        <boolProp name=\"ThreadGroup.scheduler\">true</boolProp>\n")
		fmt.Fprintf(b, "        <stringProp name=\"ThreadGroup.duration\">%d</stringProp>\n", s.Load.Duration.Seconds)
	} else {
		b.WriteString("        <boolProp name=\"ThreadGroup.scheduler\">false</boolProp>\n")
		b.WriteString("        <stringProp name=\"ThreadGroup.duration\"></stringProp>\n")
	}
	b.WriteString("        <stringProp name=\"ThreadGroup.delay\"></stringProp>\n")
	b.WriteString("      </ThreadGroup>\n")
}

func writeHTTPSampler(b *strings.Builder, s *spec.Spec, r spec.Request) {
	target, _ := url.Parse(s.Target)
	fmt.Fprintf(b, `        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="%s" enabled="true">`+"\n", esc(r.Name))
	body := rawBodyString(r)
	multipart := len(r.BodyMultipart) > 0
	if body != "" {
		b.WriteString("          <boolProp name=\"HTTPSampler.postBodyRaw\">true</boolProp>\n")
	} else {
		b.WriteString("          <boolProp name=\"HTTPSampler.postBodyRaw\">false</boolProp>\n")
	}
	b.WriteString("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\n")
	b.WriteString("            <collectionProp name=\"Arguments.arguments\">\n")
	if body != "" {
		b.WriteString("              <elementProp name=\"\" elementType=\"HTTPArgument\">\n")
		b.WriteString("                <boolProp name=\"HTTPArgument.always_encode\">false</boolProp>\n")
		fmt.Fprintf(b, "                <stringProp name=\"Argument.value\">%s</stringProp>\n", esc(body))
		b.WriteString("                <stringProp name=\"Argument.metadata\">=</stringProp>\n")
		b.WriteString("              </elementProp>\n")
	} else if multipart {
		writeMultipartTextArguments(b, r.BodyMultipart)
	} else if len(r.BodyForm) > 0 {
		writeFormArguments(b, r.BodyForm)
	} else {
		writeQueryArguments(b, r.Query)
	}
	b.WriteString("            </collectionProp>\n")
	b.WriteString("          </elementProp>\n")
	if multipart {
		writeMultipartFileArguments(b, r.BodyMultipart)
	}
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.domain\">%s</stringProp>\n", esc(target.Hostname()))
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.port\">%s</stringProp>\n", esc(target.Port()))
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.protocol\">%s</stringProp>\n", esc(target.Scheme))
	b.WriteString("          <stringProp name=\"HTTPSampler.contentEncoding\">UTF-8</stringProp>\n")
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.path\">%s</stringProp>\n", esc(r.Path))
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.method\">%s</stringProp>\n", esc(r.Method))
	b.WriteString("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\n")
	b.WriteString("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\n")
	b.WriteString("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\n")
	fmt.Fprintf(b, "          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">%s</boolProp>\n", boolLiteral(multipart))
	b.WriteString("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>\n")
	timeoutMS := ""
	if r.Timeout.Set {
		timeoutMS = fmt.Sprintf("%d", r.Timeout.Seconds*1000)
	}
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.connect_timeout\">%s</stringProp>\n", timeoutMS)
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.response_timeout\">%s</stringProp>\n", timeoutMS)
	b.WriteString("        </HTTPSamplerProxy>\n")
	b.WriteString("        <hashTree>\n")
	headers := requestHeaders(r)
	if len(headers) > 0 {
		writeHeaders(b, headers)
	}
	if r.Expect.Status > 0 {
		writeStatusAssertion(b, r.Expect.Status)
	}
	b.WriteString("        </hashTree>\n")
}

func writeWebSocketSampler(b *strings.Builder, s *spec.Spec, r spec.Request) {
	wsURL := r.WebSocket.URL
	if wsURL == "" {
		base := strings.TrimRight(s.Target, "/")
		path := r.Path
		if path == "" {
			path = "/"
		}
		wsURL = base + path
	}

	server, port, wsPath, useTLS := parseWebSocketURL(wsURL)
	connectTimeoutMs := 20000
	if r.WebSocket.Timeout.Set {
		connectTimeoutMs = r.WebSocket.Timeout.Seconds * 1000
	}
	readTimeoutMs := connectTimeoutMs
	closeTimeoutMs := readTimeoutMs
	if r.WebSocket.CloseTimeout.Set {
		closeTimeoutMs = r.WebSocket.CloseTimeout.Seconds * 1000
	}
	handshakeHeaders := websocketHandshakeHeaders(r.WebSocket)
	messages := r.WebSocket.Messages

	// Single request-response: one send with one expect.
	if len(messages) == 1 && messages[0].Expect != nil {
		if messages[0].Expect.Timeout.Set {
			readTimeoutMs = messages[0].Expect.Timeout.Seconds * 1000
		}
		payloadType := "Text"
		if messages[0].Type == "binary" {
			payloadType = "Binary"
		}
		writeRequestResponseSampler(b, r.Name, server, port, wsPath, useTLS, connectTimeoutMs, readTimeoutMs, messages[0].Send, payloadType, true)
		writeRequestResponseChildren(b, handshakeHeaders, &messages[0])
		return
	}

	// Multi-message: Open + Write/Read pairs + Close, wrapped in a Transaction Controller.
	fmt.Fprintf(b, `        <TransactionController guiclass="TransactionControllerGui" testclass="TransactionController" testname="%s" enabled="true">`+"\n", esc(r.Name))
	b.WriteString("          <boolProp name=\"TransactionController.includeTimers\">false</boolProp>\n")
	b.WriteString("          <boolProp name=\"TransactionController.parent\">true</boolProp>\n")
	b.WriteString("        </TransactionController>\n")
	b.WriteString("        <hashTree>\n")

	// Open connection.
	writeOpenConnectionSampler(b, r.Name+" - open", server, port, wsPath, useTLS, connectTimeoutMs, readTimeoutMs, handshakeHeaders)

	// Send/Read messages.
	for i, msg := range messages {
		if msg.Delay.Set && msg.Delay.Seconds > 0 {
			writeConstantTimer(b, msg.Delay.Seconds*1000)
		}
		msgReadTimeout := readTimeoutMs
		if msg.Expect != nil && msg.Expect.Timeout.Set {
			msgReadTimeout = msg.Expect.Timeout.Seconds * 1000
		}
		payloadType := "Text"
		if msg.Type == "binary" {
			payloadType = "Binary"
		}

		if msg.Expect != nil {
			// Send and expect response in one sampler (reuse connection from Open).
			writeRequestResponseSampler(b, fmt.Sprintf("%s - msg %d", r.Name, i), server, port, wsPath, useTLS, connectTimeoutMs, msgReadTimeout, msg.Send, payloadType, false)
			writeRequestResponseChildren(b, nil, &msg)
		} else {
			// Fire-and-forget write.
			writeSingleWriteSampler(b, fmt.Sprintf("%s - send %d", r.Name, i), connectTimeoutMs, msgReadTimeout, msg.Send, payloadType)
		}
	}

	// Close connection.
	writeCloseSampler(b, r.Name+" - close", closeTimeoutMs)

	b.WriteString("        </hashTree>\n")
}

// parseWebSocketURL extracts server, port, path, and TLS from a ws:// or wss:// URL.
func parseWebSocketURL(rawURL string) (server string, port string, path string, useTLS bool) {
	useTLS = strings.HasPrefix(rawURL, "wss://")
	cleaned := strings.TrimPrefix(strings.TrimPrefix(rawURL, "wss://"), "ws://")
	parts := strings.SplitN(cleaned, "/", 2)
	hostPort := parts[0]
	path = "/"
	if len(parts) > 1 {
		path = "/" + parts[1]
	}
	if strings.Contains(hostPort, ":") {
		hp := strings.SplitN(hostPort, ":", 2)
		server = hp[0]
		port = hp[1]
	} else {
		server = hostPort
		if useTLS {
			port = "443"
		} else {
			port = "80"
		}
	}
	return
}

func writeOpenConnectionSampler(b *strings.Builder, name, server, port, path string, useTLS bool, connectTimeoutMs, readTimeoutMs int, headers map[string]string) {
	fmt.Fprintf(b, `          <eu.luminis.jmeter.wssampler.OpenWebSocketSampler guiclass="eu.luminis.jmeter.wssampler.OpenWebSocketSamplerGui" testclass="eu.luminis.jmeter.wssampler.OpenWebSocketSampler" testname="%s" enabled="true">`+"\n", esc(name))
	fmt.Fprintf(b, "            <stringProp name=\"server\">%s</stringProp>\n", esc(server))
	fmt.Fprintf(b, "            <stringProp name=\"port\">%s</stringProp>\n", esc(port))
	fmt.Fprintf(b, "            <stringProp name=\"path\">%s</stringProp>\n", esc(path))
	fmt.Fprintf(b, "            <boolProp name=\"TLS\">%t</boolProp>\n", useTLS)
	fmt.Fprintf(b, "            <stringProp name=\"connectTimeout\">%d</stringProp>\n", connectTimeoutMs)
	fmt.Fprintf(b, "            <stringProp name=\"readTimeout\">%d</stringProp>\n", readTimeoutMs)
	b.WriteString("          </eu.luminis.jmeter.wssampler.OpenWebSocketSampler>\n")
	if len(headers) == 0 {
		b.WriteString("          <hashTree/>\n")
		return
	}
	b.WriteString("          <hashTree>\n")
	writeWebSocketHeaderManager(b, "            ", "WebSocket Handshake Headers", headers)
	b.WriteString("          </hashTree>\n")
}

func writeRequestResponseSampler(b *strings.Builder, name, server, port, path string, useTLS bool, connectTimeoutMs, readTimeoutMs int, requestData, payloadType string, createNew bool) {
	fmt.Fprintf(b, `        <eu.luminis.jmeter.wssampler.RequestResponseWebSocketSampler guiclass="eu.luminis.jmeter.wssampler.RequestResponseWebSocketSamplerGui" testclass="eu.luminis.jmeter.wssampler.RequestResponseWebSocketSampler" testname="%s" enabled="true">`+"\n", esc(name))
	fmt.Fprintf(b, "          <boolProp name=\"createNewConnection\">%t</boolProp>\n", createNew)
	fmt.Fprintf(b, "          <boolProp name=\"TLS\">%t</boolProp>\n", useTLS)
	fmt.Fprintf(b, "          <stringProp name=\"server\">%s</stringProp>\n", esc(server))
	fmt.Fprintf(b, "          <stringProp name=\"port\">%s</stringProp>\n", esc(port))
	fmt.Fprintf(b, "          <stringProp name=\"path\">%s</stringProp>\n", esc(path))
	fmt.Fprintf(b, "          <stringProp name=\"connectTimeout\">%d</stringProp>\n", connectTimeoutMs)
	fmt.Fprintf(b, "          <stringProp name=\"readTimeout\">%d</stringProp>\n", readTimeoutMs)
	fmt.Fprintf(b, "          <stringProp name=\"requestData\">%s</stringProp>\n", esc(requestData))
	fmt.Fprintf(b, "          <stringProp name=\"payloadType\">%s</stringProp>\n", payloadType)
	b.WriteString("        </eu.luminis.jmeter.wssampler.RequestResponseWebSocketSampler>\n")
}

func writeRequestResponseChildren(b *strings.Builder, headers map[string]string, msg *spec.WSMessage) {
	hasAssertion := msg != nil && msg.Expect != nil && msg.Expect.Contains != ""
	if len(headers) == 0 && !hasAssertion {
		b.WriteString("        <hashTree/>\n")
		return
	}
	b.WriteString("        <hashTree>\n")
	if len(headers) > 0 {
		writeWebSocketHeaderManager(b, "          ", "WebSocket Handshake Headers", headers)
	}
	if hasAssertion {
		writeResponseAssertionElement(b, "          ", *msg)
	}
	b.WriteString("        </hashTree>\n")
}

func websocketHandshakeHeaders(ws spec.WebSocket) map[string]string {
	headers := map[string]string{}
	for key, value := range ws.Headers {
		headers[key] = value
	}
	if subprotocol := strings.TrimSpace(ws.Subprotocol); subprotocol != "" && !hasHeader(headers, "Sec-WebSocket-Protocol") {
		headers["Sec-WebSocket-Protocol"] = subprotocol
	}
	return headers
}

func writeWebSocketHeaderManager(b *strings.Builder, indent string, testName string, headers map[string]string) {
	fmt.Fprintf(b, `%s<HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="%s" enabled="true">`+"\n", indent, esc(testName))
	fmt.Fprintf(b, "%s  <collectionProp name=\"HeaderManager.headers\">\n", indent)
	for _, key := range sortedKeys(headers) {
		fmt.Fprintf(b, "%s    <elementProp name=\"\" elementType=\"Header\">\n", indent)
		fmt.Fprintf(b, "%s      <stringProp name=\"Header.name\">%s</stringProp>\n", indent, esc(key))
		fmt.Fprintf(b, "%s      <stringProp name=\"Header.value\">%s</stringProp>\n", indent, esc(headers[key]))
		fmt.Fprintf(b, "%s    </elementProp>\n", indent)
	}
	fmt.Fprintf(b, "%s  </collectionProp>\n", indent)
	fmt.Fprintf(b, "%s</HeaderManager>\n", indent)
	fmt.Fprintf(b, "%s<hashTree/>\n", indent)
}

func writeSingleWriteSampler(b *strings.Builder, name string, connectTimeoutMs, readTimeoutMs int, requestData, payloadType string) {
	fmt.Fprintf(b, `          <eu.luminis.jmeter.wssampler.SingleWriteWebSocketSampler guiclass="eu.luminis.jmeter.wssampler.SingleWriteWebSocketSamplerGui" testclass="eu.luminis.jmeter.wssampler.SingleWriteWebSocketSampler" testname="%s" enabled="true">`+"\n", esc(name))
	fmt.Fprintf(b, "            <boolProp name=\"createNewConnection\">false</boolProp>\n")
	fmt.Fprintf(b, "            <stringProp name=\"connectTimeout\">%d</stringProp>\n", connectTimeoutMs)
	fmt.Fprintf(b, "            <stringProp name=\"readTimeout\">%d</stringProp>\n", readTimeoutMs)
	fmt.Fprintf(b, "            <stringProp name=\"requestData\">%s</stringProp>\n", esc(requestData))
	fmt.Fprintf(b, "            <stringProp name=\"payloadType\">%s</stringProp>\n", payloadType)
	b.WriteString("          </eu.luminis.jmeter.wssampler.SingleWriteWebSocketSampler>\n")
	b.WriteString("          <hashTree/>\n")
}

func writeCloseSampler(b *strings.Builder, name string, readTimeoutMs int) {
	fmt.Fprintf(b, `          <eu.luminis.jmeter.wssampler.CloseWebSocketSampler guiclass="eu.luminis.jmeter.wssampler.CloseWebSocketSamplerGui" testclass="eu.luminis.jmeter.wssampler.CloseWebSocketSampler" testname="%s" enabled="true">`+"\n", esc(name))
	fmt.Fprintf(b, "            <stringProp name=\"readTimeout\">%d</stringProp>\n", readTimeoutMs)
	b.WriteString("            <boolProp name=\"createNewConnection\">false</boolProp>\n")
	b.WriteString("          </eu.luminis.jmeter.wssampler.CloseWebSocketSampler>\n")
	b.WriteString("          <hashTree/>\n")
}

func writeConstantTimer(b *strings.Builder, delayMs int) {
	b.WriteString("          <ConstantTimer guiclass=\"ConstantTimerGui\" testclass=\"ConstantTimer\" testname=\"Delay\" enabled=\"true\">\n")
	fmt.Fprintf(b, "            <stringProp name=\"ConstantTimer.delay\">%d</stringProp>\n", delayMs)
	b.WriteString("          </ConstantTimer>\n")
	b.WriteString("          <hashTree/>\n")
}

func writeResponseAssertionElement(b *strings.Builder, indent string, msg spec.WSMessage) {
	b.WriteString(indent + "<ResponseAssertion guiclass=\"AssertionGui\" testclass=\"ResponseAssertion\" testname=\"contains assertion\" enabled=\"true\">\n")
	b.WriteString(indent + "  <collectionProp name=\"Asserion.test_strings\">\n")
	fmt.Fprintf(b, "%s    <stringProp name=\"0\">%s</stringProp>\n", indent, esc(msg.Expect.Contains))
	b.WriteString(indent + "  </collectionProp>\n")
	b.WriteString(indent + "  <stringProp name=\"Assertion.test_field\">Assertion.response_data</stringProp>\n")
	b.WriteString(indent + "  <intProp name=\"Assertion.test_type\">16</intProp>\n") // 16 = Substring
	b.WriteString(indent + "</ResponseAssertion>\n")
	b.WriteString(indent + "<hashTree/>\n")
}

func scriptString(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return escaped
}

func writeQueryArguments(b *strings.Builder, query map[string]string) {
	keys := sortedKeys(query)
	for _, key := range keys {
		fmt.Fprintf(b, "              <elementProp name=\"%s\" elementType=\"HTTPArgument\">\n", esc(key))
		b.WriteString("                <boolProp name=\"HTTPArgument.always_encode\">true</boolProp>\n")
		fmt.Fprintf(b, "                <stringProp name=\"Argument.name\">%s</stringProp>\n", esc(key))
		fmt.Fprintf(b, "                <stringProp name=\"Argument.value\">%s</stringProp>\n", esc(query[key]))
		b.WriteString("                <stringProp name=\"Argument.metadata\">=</stringProp>\n")
		b.WriteString("                <boolProp name=\"HTTPArgument.use_equals\">true</boolProp>\n")
		b.WriteString("              </elementProp>\n")
	}
}

func writeFormArguments(b *strings.Builder, fields map[string]string) {
	keys := sortedKeys(fields)
	for _, key := range keys {
		fmt.Fprintf(b, "              <elementProp name=\"%s\" elementType=\"HTTPArgument\">\n", esc(key))
		b.WriteString("                <boolProp name=\"HTTPArgument.always_encode\">true</boolProp>\n")
		fmt.Fprintf(b, "                <stringProp name=\"Argument.name\">%s</stringProp>\n", esc(key))
		fmt.Fprintf(b, "                <stringProp name=\"Argument.value\">%s</stringProp>\n", esc(fields[key]))
		b.WriteString("                <stringProp name=\"Argument.metadata\">=</stringProp>\n")
		b.WriteString("                <boolProp name=\"HTTPArgument.use_equals\">true</boolProp>\n")
		b.WriteString("              </elementProp>\n")
	}
}

func writeMultipartTextArguments(b *strings.Builder, parts []spec.MultipartPart) {
	for _, part := range parts {
		if part.Value == nil {
			continue
		}
		fmt.Fprintf(b, "              <elementProp name=\"%s\" elementType=\"HTTPArgument\">\n", esc(part.Name))
		b.WriteString("                <boolProp name=\"HTTPArgument.always_encode\">false</boolProp>\n")
		fmt.Fprintf(b, "                <stringProp name=\"Argument.name\">%s</stringProp>\n", esc(part.Name))
		fmt.Fprintf(b, "                <stringProp name=\"Argument.value\">%s</stringProp>\n", esc(*part.Value))
		b.WriteString("                <stringProp name=\"Argument.metadata\">=</stringProp>\n")
		b.WriteString("                <boolProp name=\"HTTPArgument.use_equals\">true</boolProp>\n")
		b.WriteString("              </elementProp>\n")
	}
}

func writeMultipartFileArguments(b *strings.Builder, parts []spec.MultipartPart) {
	b.WriteString("          <elementProp name=\"HTTPsampler.Files\" elementType=\"HTTPFileArgs\">\n")
	b.WriteString("            <collectionProp name=\"HTTPFileArgs.files\">\n")
	for _, part := range parts {
		if part.File == "" {
			continue
		}
		fmt.Fprintf(b, "              <elementProp name=\"%s\" elementType=\"HTTPFileArg\">\n", esc(part.Name))
		fmt.Fprintf(b, "                <stringProp name=\"File.path\">%s</stringProp>\n", esc(part.File))
		fmt.Fprintf(b, "                <stringProp name=\"File.paramname\">%s</stringProp>\n", esc(part.Name))
		fmt.Fprintf(b, "                <stringProp name=\"File.mimetype\">%s</stringProp>\n", esc(part.ContentType))
		b.WriteString("              </elementProp>\n")
	}
	b.WriteString("            </collectionProp>\n")
	b.WriteString("          </elementProp>\n")
}

func writeHeaders(b *strings.Builder, headers map[string]string) {
	b.WriteString("          <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Headers\" enabled=\"true\">\n")
	b.WriteString("            <collectionProp name=\"HeaderManager.headers\">\n")
	for _, key := range sortedKeys(headers) {
		b.WriteString("              <elementProp name=\"\" elementType=\"Header\">\n")
		fmt.Fprintf(b, "                <stringProp name=\"Header.name\">%s</stringProp>\n", esc(key))
		fmt.Fprintf(b, "                <stringProp name=\"Header.value\">%s</stringProp>\n", esc(headers[key]))
		b.WriteString("              </elementProp>\n")
	}
	b.WriteString("            </collectionProp>\n")
	b.WriteString("          </HeaderManager>\n")
	b.WriteString("          <hashTree/>\n")
}

func writeStatusAssertion(b *strings.Builder, status int) {
	fmt.Fprintf(b, "          <ResponseAssertion guiclass=\"AssertionGui\" testclass=\"ResponseAssertion\" testname=\"Expect HTTP %d\" enabled=\"true\">\n", status)
	b.WriteString("            <collectionProp name=\"Assertion.test_strings\">\n")
	fmt.Fprintf(b, "              <stringProp name=\"%d\">%d</stringProp>\n", status, status)
	b.WriteString("            </collectionProp>\n")
	b.WriteString("            <stringProp name=\"Assertion.custom_message\"></stringProp>\n")
	b.WriteString("            <stringProp name=\"Assertion.test_field\">Assertion.response_code</stringProp>\n")
	b.WriteString("            <boolProp name=\"Assertion.assume_success\">false</boolProp>\n")
	b.WriteString("            <intProp name=\"Assertion.test_type\">8</intProp>\n")
	b.WriteString("          </ResponseAssertion>\n")
	b.WriteString("          <hashTree/>\n")
}

func rawBodyString(r spec.Request) string {
	if r.BodyText != "" {
		return r.BodyText
	}
	if r.BodyJSON != nil {
		return bodyString(r.BodyJSON)
	}
	return bodyString(r.Body)
}

func bodyString(body any) string {
	if body == nil {
		return ""
	}
	if value, ok := body.(string); ok {
		return value
	}
	data, err := json.Marshal(jsonable(body))
	if err != nil {
		return fmt.Sprintf("%v", body)
	}
	return string(data)
}

func jsonable(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		out := map[string]any{}
		for key, item := range typed {
			out[key] = jsonable(item)
		}
		return out
	case map[any]any:
		out := map[string]any{}
		for key, item := range typed {
			out[fmt.Sprintf("%v", key)] = jsonable(item)
		}
		return out
	case []any:
		out := make([]any, len(typed))
		for index, item := range typed {
			out[index] = jsonable(item)
		}
		return out
	default:
		return value
	}
}

func requestHeaders(r spec.Request) map[string]string {
	if len(r.BodyMultipart) > 0 {
		headers := map[string]string{}
		for key, value := range r.Headers {
			if strings.EqualFold(key, "content-type") {
				continue
			}
			headers[key] = value
		}
		return headers
	}
	if len(r.BodyForm) == 0 || hasHeader(r.Headers, "content-type") {
		return r.Headers
	}
	headers := map[string]string{}
	for key, value := range r.Headers {
		headers[key] = value
	}
	headers["Content-Type"] = "application/x-www-form-urlencoded"
	return headers
}

func boolLiteral(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func hasHeader(headers map[string]string, name string) bool {
	for key := range headers {
		if strings.EqualFold(key, name) {
			return true
		}
	}
	return false
}

func esc(value string) string {
	var b bytes.Buffer
	_ = xml.EscapeText(&b, []byte(value))
	return b.String()
}

func sortedKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedDataSetNames(values map[string]spec.DataSet) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func boolString(value *bool, defaultValue bool) string {
	if value == nil {
		if defaultValue {
			return "true"
		}
		return "false"
	}
	if *value {
		return "true"
	}
	return "false"
}

func shareMode(value string) string {
	switch value {
	case "thread":
		return "Current thread"
	case "group":
		return "Current thread group"
	default:
		return "All threads"
	}
}
