package jmx

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/devaryakjha/loadwright/internal/spec"
)

func SafeName(value string) string {
	re := regexp.MustCompile(`[^A-Za-z0-9_.-]+`)
	cleaned := strings.Trim(re.ReplaceAllString(strings.TrimSpace(value), "-"), "-")
	if cleaned == "" {
		return "test"
	}
	return cleaned
}

func Compile(s *spec.Spec, outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(Render(s)), 0o644)
}

func Render(s *spec.Spec) string {
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString(`<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">` + "\n")
	b.WriteString("  <hashTree>\n")
	writeTestPlan(&b, s)
	b.WriteString("    <hashTree>\n")
	writeThreadGroup(&b, s)
	b.WriteString("      <hashTree>\n")
	for _, request := range s.Requests {
		writeHTTPSampler(&b, s, request)
	}
	b.WriteString("      </hashTree>\n")
	b.WriteString("    </hashTree>\n")
	b.WriteString("  </hashTree>\n")
	b.WriteString("</jmeterTestPlan>\n")
	return b.String()
}

func writeTestPlan(b *strings.Builder, s *spec.Spec) {
	fmt.Fprintf(b, `    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="%s" enabled="true">`+"\n", esc(s.Name))
	b.WriteString("      <stringProp name=\"TestPlan.comments\">Generated by Loadwright from a YAML spec.</stringProp>\n")
	b.WriteString("      <boolProp name=\"TestPlan.functional_mode\">false</boolProp>\n")
	b.WriteString("      <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>\n")
	b.WriteString("      <elementProp name=\"TestPlan.user_defined_variables\" elementType=\"Arguments\" guiclass=\"ArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\n")
	b.WriteString("        <collectionProp name=\"Arguments.arguments\"/>\n")
	b.WriteString("      </elementProp>\n")
	b.WriteString("      <stringProp name=\"TestPlan.user_define_classpath\"></stringProp>\n")
	b.WriteString("    </TestPlan>\n")
}

func writeThreadGroup(b *strings.Builder, s *spec.Spec) {
	fmt.Fprintf(b, `      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="%s users" enabled="true">`+"\n", esc(s.Name))
	b.WriteString("        <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>\n")
	b.WriteString("        <elementProp name=\"ThreadGroup.main_controller\" elementType=\"LoopController\" guiclass=\"LoopControlPanel\" testclass=\"LoopController\" testname=\"Loop Controller\" enabled=\"true\">\n")
	continueForever := "false"
	loops := "1"
	if s.Load.Duration.Set {
		continueForever = "true"
		loops = "-1"
	} else if s.Load.Loops != nil {
		loops = fmt.Sprintf("%d", *s.Load.Loops)
	}
	fmt.Fprintf(b, "          <boolProp name=\"LoopController.continue_forever\">%s</boolProp>\n", continueForever)
	fmt.Fprintf(b, "          <stringProp name=\"LoopController.loops\">%s</stringProp>\n", loops)
	b.WriteString("        </elementProp>\n")
	fmt.Fprintf(b, "        <stringProp name=\"ThreadGroup.num_threads\">%d</stringProp>\n", s.Load.Users)
	fmt.Fprintf(b, "        <stringProp name=\"ThreadGroup.ramp_time\">%d</stringProp>\n", s.Load.RampUp.Seconds)
	b.WriteString("        <boolProp name=\"ThreadGroup.same_user_on_next_iteration\">true</boolProp>\n")
	if s.Load.Duration.Set {
		b.WriteString("        <boolProp name=\"ThreadGroup.scheduler\">true</boolProp>\n")
		fmt.Fprintf(b, "        <stringProp name=\"ThreadGroup.duration\">%d</stringProp>\n", s.Load.Duration.Seconds)
	} else {
		b.WriteString("        <boolProp name=\"ThreadGroup.scheduler\">false</boolProp>\n")
		b.WriteString("        <stringProp name=\"ThreadGroup.duration\"></stringProp>\n")
	}
	b.WriteString("        <stringProp name=\"ThreadGroup.delay\"></stringProp>\n")
	b.WriteString("      </ThreadGroup>\n")
}

func writeHTTPSampler(b *strings.Builder, s *spec.Spec, r spec.Request) {
	target, _ := url.Parse(s.Target)
	fmt.Fprintf(b, `        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="%s" enabled="true">`+"\n", esc(r.Name))
	body := bodyString(r.Body)
	if body != "" {
		b.WriteString("          <boolProp name=\"HTTPSampler.postBodyRaw\">true</boolProp>\n")
	} else {
		b.WriteString("          <boolProp name=\"HTTPSampler.postBodyRaw\">false</boolProp>\n")
	}
	b.WriteString("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">\n")
	b.WriteString("            <collectionProp name=\"Arguments.arguments\">\n")
	if body != "" {
		b.WriteString("              <elementProp name=\"\" elementType=\"HTTPArgument\">\n")
		b.WriteString("                <boolProp name=\"HTTPArgument.always_encode\">false</boolProp>\n")
		fmt.Fprintf(b, "                <stringProp name=\"Argument.value\">%s</stringProp>\n", esc(body))
		b.WriteString("                <stringProp name=\"Argument.metadata\">=</stringProp>\n")
		b.WriteString("              </elementProp>\n")
	} else {
		writeQueryArguments(b, r.Query)
	}
	b.WriteString("            </collectionProp>\n")
	b.WriteString("          </elementProp>\n")
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.domain\">%s</stringProp>\n", esc(target.Hostname()))
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.port\">%s</stringProp>\n", esc(target.Port()))
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.protocol\">%s</stringProp>\n", esc(target.Scheme))
	b.WriteString("          <stringProp name=\"HTTPSampler.contentEncoding\">UTF-8</stringProp>\n")
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.path\">%s</stringProp>\n", esc(r.Path))
	fmt.Fprintf(b, "          <stringProp name=\"HTTPSampler.method\">%s</stringProp>\n", esc(r.Method))
	b.WriteString("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>\n")
	b.WriteString("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>\n")
	b.WriteString("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>\n")
	b.WriteString("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>\n")
	b.WriteString("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>\n")
	b.WriteString("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>\n")
	b.WriteString("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>\n")
	b.WriteString("        </HTTPSamplerProxy>\n")
	b.WriteString("        <hashTree>\n")
	if len(r.Headers) > 0 {
		writeHeaders(b, r.Headers)
	}
	if r.Expect.Status > 0 {
		writeStatusAssertion(b, r.Expect.Status)
	}
	b.WriteString("        </hashTree>\n")
}

func writeQueryArguments(b *strings.Builder, query map[string]string) {
	keys := sortedKeys(query)
	for _, key := range keys {
		fmt.Fprintf(b, "              <elementProp name=\"%s\" elementType=\"HTTPArgument\">\n", esc(key))
		b.WriteString("                <boolProp name=\"HTTPArgument.always_encode\">true</boolProp>\n")
		fmt.Fprintf(b, "                <stringProp name=\"Argument.name\">%s</stringProp>\n", esc(key))
		fmt.Fprintf(b, "                <stringProp name=\"Argument.value\">%s</stringProp>\n", esc(query[key]))
		b.WriteString("                <stringProp name=\"Argument.metadata\">=</stringProp>\n")
		b.WriteString("                <boolProp name=\"HTTPArgument.use_equals\">true</boolProp>\n")
		b.WriteString("              </elementProp>\n")
	}
}

func writeHeaders(b *strings.Builder, headers map[string]string) {
	b.WriteString("          <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\" testname=\"HTTP Headers\" enabled=\"true\">\n")
	b.WriteString("            <collectionProp name=\"HeaderManager.headers\">\n")
	for _, key := range sortedKeys(headers) {
		b.WriteString("              <elementProp name=\"\" elementType=\"Header\">\n")
		fmt.Fprintf(b, "                <stringProp name=\"Header.name\">%s</stringProp>\n", esc(key))
		fmt.Fprintf(b, "                <stringProp name=\"Header.value\">%s</stringProp>\n", esc(headers[key]))
		b.WriteString("              </elementProp>\n")
	}
	b.WriteString("            </collectionProp>\n")
	b.WriteString("          </HeaderManager>\n")
	b.WriteString("          <hashTree/>\n")
}

func writeStatusAssertion(b *strings.Builder, status int) {
	fmt.Fprintf(b, "          <ResponseAssertion guiclass=\"AssertionGui\" testclass=\"ResponseAssertion\" testname=\"Expect HTTP %d\" enabled=\"true\">\n", status)
	b.WriteString("            <collectionProp name=\"Assertion.test_strings\">\n")
	fmt.Fprintf(b, "              <stringProp name=\"%d\">%d</stringProp>\n", status, status)
	b.WriteString("            </collectionProp>\n")
	b.WriteString("            <stringProp name=\"Assertion.custom_message\"></stringProp>\n")
	b.WriteString("            <stringProp name=\"Assertion.test_field\">Assertion.response_code</stringProp>\n")
	b.WriteString("            <boolProp name=\"Assertion.assume_success\">false</boolProp>\n")
	b.WriteString("            <intProp name=\"Assertion.test_type\">8</intProp>\n")
	b.WriteString("          </ResponseAssertion>\n")
	b.WriteString("          <hashTree/>\n")
}

func bodyString(body any) string {
	if body == nil {
		return ""
	}
	if value, ok := body.(string); ok {
		return value
	}
	data, err := json.Marshal(jsonable(body))
	if err != nil {
		return fmt.Sprintf("%v", body)
	}
	return string(data)
}

func jsonable(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		out := map[string]any{}
		for key, item := range typed {
			out[key] = jsonable(item)
		}
		return out
	case map[any]any:
		out := map[string]any{}
		for key, item := range typed {
			out[fmt.Sprintf("%v", key)] = jsonable(item)
		}
		return out
	case []any:
		out := make([]any, len(typed))
		for index, item := range typed {
			out[index] = jsonable(item)
		}
		return out
	default:
		return value
	}
}

func esc(value string) string {
	var b bytes.Buffer
	_ = xml.EscapeText(&b, []byte(value))
	return b.String()
}

func sortedKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
